openapi: 3.0.3
info:
  title: Farmacias de Turno + Vademécum - API MVP v2
  version: "0.2.0"
servers:
  - url: http://localhost:8000
paths:
  /health:
    get:
      summary: Estado
      responses:
        '200':
          description: OK
  /farmacias:
    get:
      summary: Buscar farmacias (turno / abierto ahora)
      parameters:
        - in: query
          name: region
          schema: { type: string }
        - in: query
          name: comuna
          schema: { type: string }
        - in: query
          name: abierto
          schema: { type: boolean }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100 }
      responses:
        '200': { description: Lista de farmacias }
        '502': { description: Error fuente oficial }
  /medicamentos:
    get:
      summary: Fichas informativas (no prescriptivo)
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 50 }
      responses:
        '200': { description: Resultados }
  /chat:
    post:
      summary: Chat con herramientas + guardrails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message: { type: string }
      responses:
        '200': { description: Respuesta del asistente }
